/**
 * Checks if the LLM's guess is correct regardless of case
 * 
 * @param guess The string response generated by the LLM
 * @param answer The correct answer to the current drawing prompt
 * @returns {boolean} Returns True if answer is found in guess, False otherwise
 */

export const checkGuess = (guess: string, answer: string): boolean => {
  return guess.toLowerCase().includes(answer.toLowerCase());
};
