/**
 * Checks if the LLM's guess is correct regardless of case
 * 
 * @param answer The correct answer to the current drawing prompt
 * @param guess The string response generated by the LLM
 * @returns {boolean} Returns True if answer is found in guess, False otherwise
 */

